version: "2.1"
services:
  web:
    build: .
    restart: unless-stopped
    container_name: notes_container
    environment:
      - WEB_PORT=${WEB_PORT}

      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}

    command: sh -c "aerich upgrade && uvicorn main:app --reload --host 0.0.0.0 --port 5000"
    ports:
      - 0.0.0.0:${WEB_PORT}:5000
    depends_on:
      - postgres
    volumes:
      - ./src:/src

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_container
    ports:
      - 0.0.0.0:${POSTGRES_PORT}:5600
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
